services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - backend-network
      - frontend-network  # Connects backend to frontend

    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/studentdb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - frontend-network  # Separate network for frontend-backend communication

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network  # Separate network for backend-database communication

volumes:
  mongo-data:  # Define persistent volume for MongoDB
      driver: local

networks:
  frontend-network:  # Separate network for frontend-backend communication
            driver: bridge

  backend-network:  # Separate network for backend-database communication
           driver: bridge
